she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('<int:pk>/update', views.StoryUpdateView.as_view(), name='update'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path
from users import url as userUrl
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', include('news.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include(userUrl)),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username


class Profile(models.Model):
    about_me = models.TextField()
    image = models.ImageField(upload_to='profile_image', null=True, blank=True)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

she_codes_news/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class EditProfileForm(forms.Form):
    username = forms.CharField()
    about_me = forms.CharField(widget=forms.Textarea())
    image = forms.ImageField(required=False)

    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def clean_username(self):
        """
        This function throws an exception if the username has already been
        taken by another user
        """

        username = self.cleaned_data['username']
        if username != self.original_username:
            if CustomUser.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'A user with that username already exists.')
        return username

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser, Profile
from .forms import CustomUserCreationForm, EditProfileForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from news.models import NewsStory


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'


@login_required
def profile(request, username):
    user = get_object_or_404(CustomUser, username=username)
    profile = get_object_or_404(Profile, user=user)
    posts = NewsStory.objects.all().filter(author=user)
    return render(request, 'users/profile.html', {'profile': profile, 'user': user, 'posts': posts})


@login_required
def edit_profile(request):
    if request.method == "POST":
        # request.user.username is the original username
        form = EditProfileForm(request.user.username, request.POST, request.FILES)
        if form.is_valid():
            about_me = form.cleaned_data["about_me"]
            username = form.cleaned_data["username"]
            image = form.cleaned_data["image"]

            user = CustomUser.objects.get(id=request.user.id)
            profile = Profile.objects.get(user=user)
            user.username = username
            user.save()
            profile.about_me = about_me
            if image:
                profile.image = image
            profile.save()
            return redirect("users:profile", username=user.username)
    else:
        form = EditProfileForm(request.user.username)  # <-- add also here
    return render(request, "users/edit_profile.html", {'form': form})

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% block content %}
    <h2 class="page_title">Create Account</h2> 
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Create Account</button>
    </form>
    {% endblock %}

she_codes_news/users/templates/users/edit_profile.html
<!-- templates/users/edit_profile.html -->
{% extends 'base.html' %}

{% block head_title %}Edit profile{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <h2 class="my-5">Edit profile</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.username.label_tag }}
                        <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}"
                               id="id_username"
                               name="username" value='{{ form.username.value|default:user.username }}'>
                        {% if form.username.errors %}
                            <div class="invalid-feedback">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.about_me.label_tag }}
                        <textarea type="text" class="form-control {% if form.about_me.errors %}is-invalid{% endif %}"
                                  id="id_about_me"
                                  name="about_me" value='{{ form.about_me.value }}' rows="5"></textarea>
                        {% if form.about_me.errors %}
                            <div class="invalid-feedback">{{ form.about_me.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.image.label_tag }}<br>
                        <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image"
                               name="image"
                               accept="image/*">
                        {% if form.image.errors %}
                            <div class="invalid-feedback">{{ form.image.errors }}</div>
                        {% endif %}
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                <br>
            </div>
        </div>
    </div>
{% endblock content %}

she_codes_news/users/templates/users/profile.html
<!-- templates/users/profile.html -->
{% extends 'base.html' %}
{% load static %}

{% block head_title %}{{ user.username }} | Django Blog{% endblock head_title %}

{% block content %}
    <div class="container-fluid mt-5">
        <div class="row">
            <div class="card col-lg-6 offset-lg-3 mb-3">
                <div class="row">
                    {% if user.profile.image %}
                        <img class="card-img-top col-sm-3 col-4 my-3" src="{{ profile.image.url }}"
                             alt="{{ user.username }}">
                    {% else %}
                        <img class="card-img-top col-sm-3 col-4 my-3" src="{% static 'img/avatar.svg' %}"
                             alt="{{ user.username }}">
                    {% endif %}
                    <div class="card-body col-9">
                        <h2 class="card-title my-3">{{ user.username }}</h2>
                        <p>Last login on: {{ user.last_login }}</p>
                        <p class="card-text">{{ user.profile.about_me }}</p>
                    </div>

                    <p><a href="{% url 'users:edit_profile' %}">Edit your profile</a></p>
                </div>
            </div>
        </div>
    </div>

    <!-- Last Story -->
    <div class="row my-4">

        {% if posts %}
            {% for story in posts %}

                <div class="col-md-4">
                    <div class="card mx-2 my-2" style="width: 18rem;" id="story-card-{{ position }}">
                        <img src="{{ story.image.url }}" class="card-img-top"
                             style="min-height: 250px;">

                        <div class="card-body">
                            <h5 class="card-title">{{ story.title }}</h5>
                            <h6>by {{ story.author }}</h6>
                            <p class="card-text">{{ story.pub_date|date:"d-M-Y" }}</p>
                          
                            <a href="{% url 'news:story' story.id %}" class="btn btn-primary">Read more</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}