she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('<int:pk>/update', views.StoryUpdateView.as_view(), name='update'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path
from users import url as userUrl
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', include('news.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include(userUrl)),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>She Codes News</title>
    <meta name="description" content="">
    <meta name="author" content="Hayley van Waas">
    <meta name="author" content="Sahar">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block stylesheets %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

</head>

<body>

{% include './nav.html' %}


<div class="container">
    <!-- content blocks here -->
    {% block content %}{% endblock %} </div>
</body>
</html>

she_codes_news/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url 'news:index' %}">
            <img src="/files/logo/Purple_no_circle.svg" alt="Purple_no_circle.svg" width="110" height="55">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="Home" href="{% url 'news:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:index' %}">News</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">


                        <a href="{% url 'users:profile' request.user.username %}"
                           class="nav-item nav-link {% if request.user.username in request.path %}active{% endif %}">
                            Profile
                        </a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:createAccount' %}">New Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>