she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('<int:pk>/update', views.StoryUpdateView.as_view(), name='update'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path
from users import url as userUrl
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', include('news.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include(userUrl)),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='news_image', null=True, blank=True)


class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    story = models.ForeignKey(
        NewsStory,
        related_name="comments",
        on_delete=models.CASCADE
    )
    text = models.TextField(null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return 'Comment by {}'.format(self.name)

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Comment


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'image']
        widgets = {
            'pub_date': forms.DateInput(
                format='%m/%d/%Y',
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
            'title': forms.TextInput(  # Use TextInput for CharField
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter a title',
                }
            ),

            'content': forms.Textarea(  # Use TextInput for CharField
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter a content',
                }
            ),
            'image': forms.FileInput(  # Use TextInput for CharField
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter an image url',
                },
            ),
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Add your comment',
                }
            ),
            'email': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter your email address',
                }
            ),
            'name': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter your name',
                }
            ),
        }

she_codes_news/news/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views import generic, View
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from .models import NewsStory, Comment
from .forms import StoryForm, CommentForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()[3:]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by(
            "-pub_date")[:3]
        return context


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]

        form = CommentForm()
        post = get_object_or_404(NewsStory, pk=pk)
        comments = post.comments.all()

        context['story'] = post
        context['comments'] = comments
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        post = NewsStory.objects.filter(id=self.kwargs['pk'])[0]
        comments = post.comments.all()

        context['story'] = post
        context['comments'] = comments
        context['form'] = form

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            content = form.cleaned_data['text']

            comment = Comment.objects.create(
                name=name, email=email, text=content, story=post
            )

            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)

        return self.render_to_response(context=context)


@method_decorator(login_required, name='dispatch')
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class StoryUpdateView(View):
    model = NewsStory
    form_class = StoryForm
    template_name = 'news/updateStory.html'
    success_url = "/news/"

    def get(self, request, pk):
        post = get_object_or_404(NewsStory, id=pk, author=request.user)
        form = StoryForm(instance=post)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        post = get_object_or_404(NewsStory, id=pk, author=request.user)
        form = StoryForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})

she_codes_news/news/templates/news/createComment.html
{% extends "base.html"%}
{% block content %}

    <form action="" method="post"> 
        {% csrf_token %}        
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Add Comment">
    </form>

    {% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html"%}
{% block content %}

    <form action="" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}        
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="submit">
    </form>

    {% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}


    <div class="d-flex align-items-center flex-column justify-content-center my-4">
        <h3 class="my-4">Welcome to SheCodes Stories</h3>
        {% if request.user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'news:newStory' %}">Write New Story</a>
        {% endif %}
    </div>
    <div class="d-flex align-items-center flex-column justify-content-center my-4 bg-color1">
        <h2>Latest News</h2>
    </div>
    <!-- Last Story -->
    <div class="row my-4">

        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div class="d-flex align-items-center flex-column justify-content-center my-4 bg-color1">
        <h2>Others News</h2>
    </div>
    <!-- <div id="all-stories"> -->
    <div class="row">
        {% if latest_stories %}
            {% for story in all_stories %}

                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}


    <div class="d-flex flex-column">
        <div class="d-flex flex-column align-items-center my-4">
            <h4>{{ story.title }}</h4>
        </div>
        <div class="d-flex my-4">
            <div class="shadow-sm p-3 mb-5 bg-body rounded">
                <img src="{{ story.image.url }}" style="max-width: 350px;">
            </div>
            <div class="p-4">

                <h5>Author: {{ story.author }}</h5>
                <h6 class="my-3">Publication date: {{ story.pub_date|date:"d-M-Y"}}</h6>

                {{ story.content|linebreaks }}
                {% if request.user.is_authenticated and story.author == request.user%}
                    <a class="btn btn-primary" href="{% url 'news:update' story.id %}">Edit</a>
                {% endif %}
            </div>
        </div>


        <!-- Form to leave comment -->
        <div class="row mt-5">
            <div class="col-lg-6 offset-lg-3">
                <h3>Leave a comment</h3>
                <form method='POST'>
                    {% csrf_token %}
                    <div class="form-group">
                        <span class="ml-2"></span>{{ form.name.label_tag }}
                        <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                               id="id_name"
                               name="name" value="{{ form.name.value|default:'' }}">
                    </div>
                    <div class="form-group">
                        <span class="ml-2"></span>
                        {{ form.email.label_tag }}
                        <span class="text-muted"><small>(Your email address will not be published)</small></span>
                        <input type="text" class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                               id="id_email"
                               name="email" value="{{ form.email.value|default:'' }}">
                    </div>
                    <div class="form-group">
                        <span class="ml-2"></span>{{ form.text.label_tag }}
                        <textarea class="form-control {% if form.text.errors %}is-invalid{% endif %}" id="id_text"
                                  name="text" rows="4">{{ form.text.value|default:'' }}</textarea>
                    </div>
                    <button class="btn btn-primary ml-2 my-4" type="submit">Add Comment</button>
                </form>
            </div>
        </div>


        <!-- List of comments -->
        {% if comments %}
            <div class="row mt-5">
                <div class="col-lg-6 offset-lg-3">
                    Comment{{ comments.count|pluralize }}
                    <span class="badge badge-dark ml-2">{{ comments.count }}</span>
                </div>
                {% for comment in comments %}
                    <div class="col-lg-6 offset-lg-3 mt-2">
                        <div class="card p-2">
                            <div class="row">
                                <div class="col-12">
                                    <img class="rounded-circle mr-2" src="{% static 'img/avatar.svg' %}" alt="Avatar">
                                    <strong>{{ comment.name }}</strong> said
                                </div>
                                <div class="col-12">
                                    <p class="m-1 mt-3">{{ comment.text }}</p>
                                    <p class="text-right text-muted"><small>{{ comment.date }}</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="col-md-4">
    <div class="card mx-2 my-2" style="width: 18rem;" id="story-card-{{ position }}">
        <img src="{{ story.image.url}}" class="card-img-top"
             style="min-height: 250px;">

        <div class="card-body">
            <h5 class="card-title">{{ story.title }}</h5>
            <!-- <h4>{{ story.author }}</h4> -->
            <p class="card-text">{{ story.pub_date|date:"d-M-Y" }}</p>
            <p>
                by
                <a href="{% url 'users:profile' story.author.username %}">
                    <!-- <span class="badge bg-secondary">{{ story.author }}</span> -->
                    {{ story.author }}

                </a>
            </p>
            <a href="{% url 'news:story' story.id %}" class="btn btn-primary">Read more</a>
        </div>
    </div>
</div>

she_codes_news/news/templates/news/updateStory.html
{% extends "base.html"%}
{% block content %}
<form method="post">  
    {% csrf_token %}  
    {{ form.as_p }}  
    <input class="btn btn-primary" type="submit" value="UPDATE">  
</form> 
{% endblock %}